name: la_dinamica_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  animate_do:
  csv: ^5.0.0
  fl_chart: ^0.69.0
  flutter_riverpod: ^2.5.1
  image: ^4.1.0
  image_picker: ^0.8.4+11
  logger: ^2.5.0
  mobile_scanner: ^6.0.7
  path_provider: ^2.0.14
  pdf: ^3.10.2
  permission_handler: ^11.3.1
  printing: ^5.10.0
  qr_flutter: ^4.1.0
  share_plus: ^10.0.3
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/f=ma11.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/f=ma11.png
    - assets/images/f=ma18.png
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
