type UserAccess @model @auth(rules: [{allow: public}]) {
  id: ID!

  user_id: ID! @index
  tenant_id: ID! @index

  permissions: String
  status: Boolean
  isAdmin: Boolean

  user: User @belongsTo(fields: ["user_id"])
  tenant: Tenant @belongsTo(fields: ["tenant_id"])
}

type Evaluations @model @auth(rules: [{allow: public}]) {
  id: ID!
  name: String
  tenant_id: String

  who: [JoinMetric] @hasMany(fields: ["id"])
  examresults: [ExamResults] @hasMany(fields: ["id"])
}

type LocalPlan @model @auth(rules: [{allow: public}]) {
  id: ID!
  type: String
  clases: Int
  price: Float
  client_id: String
  defaultPlan: Boolean

  pays: [Payment] @hasMany(fields: ["id"])
}

type Payment @model @auth(rules: [{allow: public, operations: [create, read, update, delete]}]) {
  id: ID!
  plan_id: ID! @index
  composite_key: String
  user_id: Int
  amount: Float
  clases: Int
  date: AWSDate
  client_id: String
  prof_id: String
  debt: Boolean

  plan: LocalPlan @belongsTo(fields: ["plan_id"])
}

type Student @model @auth(rules: [{allow: public, operations: [create, read, update, delete]}]) {
  id: ID!
  user_id: Int
  name: String
  address: String
  age: Int
  phone: String
  birthday: AWSDate
  email: String
  image: String
  client_id: String
  
  examresults: [JoinResults] @hasMany(fields: ["id"])
}


type Attendance @model @auth(rules: [{allow: public, operations: [create, read, update, delete]}]) {
  id: ID!
  user_id: Int
  name: String
  date: AWSDate
  client_id: String
  prof_id: String
}

type User @model @auth(rules: [{allow: public, operations: [create, read, update, delete]}]) {
  user_id: ID! @primaryKey
  name: String!
  access: [UserAccess] @hasMany(fields: ["user_id"])
}

type AppPlan @model @auth(rules: [{allow: public, operations: [create, read, update, delete]}]) {
  id: ID!
  name: String
  price: Float
}

type Tenant @model @auth(rules: [{allow: public}]) {
  tenant_id: ID! @primaryKey
  name: String!
  status: Boolean
  plan: String
  who_access: [UserAccess] @hasMany(fields: ["tenant_id"])
}
 

type Product @model @auth(rules: [{allow: public, operations: [create, read, update, delete]}]) {
  id: ID!
  code: String @index(name: "byCode", queryField: "productByCode")
  name: String 
  tenant_id: ID
  price: Float
  image: String
  stock: Int
  category: String

  sale: [Sale] @hasMany(fields: ["id"])
}

type Sale @model @auth(rules: [{allow: public, operations: [create, read, update, delete]}]) {
  id: ID!
  product_id: ID!
  tenant_id: ID
  price: Float
  date: AWSDate
  profname: String
  
  product: Product @belongsTo(fields: ["product_id"])
}

type Metric @model @auth(rules: [{allow: public, operations: [create, read, update, delete]}]) {
  id: ID!
  name: String!
  tenant_id: ID!
  description: String
  type: String
  higgerBetter: Boolean

  access: [JoinMetric] @hasMany(fields: ["id"])
}

type JoinMetric @model @auth(rules: [{allow: public}]) {
  id: ID!

  metric_id: ID! @index
  evaluation_id: ID! @index
  tenant_id: ID

  metric: Metric @belongsTo(fields: ["metric_id"])
  evaluation: Evaluations @belongsTo(fields: ["evaluation_id"])
}

type ExamResults @model @auth(rules: [{allow: public, operations: [create, read, update, delete]}]) {
  id: ID!
  date: AWSDate
  prof_id: String
  tenant_id: ID
  grades: AWSJSON
  types: AWSJSON
  tscore: AWSJSON
  metric_names: AWSJSON
  higgerBetter: AWSJSON
  evaluation_id: ID! @index

  evaluation: Evaluations @belongsTo(fields: ["evaluation_id"])
  joinresult: [JoinResults] @hasMany(fields: ["id"])
}

type JoinResults @model @auth(rules: [{allow: public}]) {
  id: ID!

  student_id: ID! @index
  result_id: ID! @index
  tenant_id: ID
  date: AWSDate

  student: Student @belongsTo(fields: ["student_id"])
  result: ExamResults @belongsTo(fields: ["result_id"])
}