type UserAccess @model @auth(rules: [{allow: public}]) {
  id: ID!

  user_id: ID! @index
  tenant_id: ID! @index

  permissions: String
  status: Boolean

  user: User @belongsTo(fields: ["user_id"])
  tenant: Tenant @belongsTo(fields: ["tenant_id"])
}

type Evaluations @model @auth(rules: [{allow: public}]) {
  id: ID!
  name: String
  tenant_id: String
  who_access: [JointMetric] @hasMany(fields: ["id"])
  grades: [Grades] @hasMany(indexName: "byEvaluation", fields: ["id"])
}

type LocalPlan @model @auth(rules: [{allow: public}]) {
  id: ID!
  type: String
  clases: Int
  price: Float
  client_id: String
  defaultPlan: Boolean

  pays: [Pay] @hasMany(fields: ["id"])
}

type Student @model @auth(rules: [{allow: public, operations: [create, read, update, delete]}]) {
  id: ID!
  user_id: Int
  name: String
  address: String
  age: Int
  phone: String
  birthday: AWSDate
  email: String
  image: String
  client_id: String
  
  grades: [Grades] @hasMany(indexName: "byStudent", fields: ["id"])
  debts: [Debt] @hasMany(indexName: "debtByStudent", fields: ["id"])
}

type Pay @model @auth(rules: [{allow: public, operations: [create, read, update, delete]}]) {
  id: ID!
  plan_id: ID! @index
  composite_key: String
  user_id: Int
  amount: Float
  clases: Int
  date: AWSDate
  client_id: String
  prof_id: String
  debt: Boolean

  plan: LocalPlan @belongsTo(fields: ["plan_id"])
}

type Attendance @model @auth(rules: [{allow: public, operations: [create, read, update, delete]}]) {
  id: ID!
  user_id: Int
  name: String
  date: AWSDate
  client_id: String
  prof_id: String
}

type User @model @auth(rules: [{allow: public, operations: [create, read, update, delete]}]) {
  user_id: ID! @primaryKey
  name: String!
  access: [UserAccess] @hasMany(fields: ["user_id"])
}

type AppPlan @model @auth(rules: [{allow: public, operations: [create, read, update, delete]}]) {
  id: ID!
  name: String
  price: Float
}

type Tenant @model @auth(rules: [{allow: public}]) {
  tenant_id: ID! @primaryKey
  name: String!
  status: Boolean
  plan: String
  who_access: [UserAccess] @hasMany(fields: ["tenant_id"])
}
 
type SingleMetric @model @auth(rules: [{allow: public, operations: [create, read, update, delete]}]) {
  id: ID!
  name: String!
  tenant_id: ID!
  description: String
  metric_type: String

  access: [JointMetric] @hasMany(fields: ["id"])
  who_access: [JoinSubMetric] @hasMany(fields: ["id"])
}

type JointMetric @model @auth(rules: [{allow: public}]) {
  id: ID!

  metric_id: ID! @index
  evaluation_id: ID! @index
  tenant_id: ID

  metric: SingleMetric @belongsTo(fields: ["metric_id"])
  evaluation: Evaluations @belongsTo(fields: ["evaluation_id"])
}

type SubMetric @model @auth(rules: [{allow: public, operations: [create, read, update, delete]}]) {
  id: ID!
  name: String!
  tenant_id: ID!
  description: String
  metric_type: String

  access: [JoinSubMetric] @hasMany(fields: ["id"])
}

type JoinSubMetric @model @auth(rules: [{allow: public}]) {
  id: ID!

  metric_id: ID! @index
  submetric_id: ID! @index
  tenant_id: ID

  submetric: SubMetric @belongsTo(fields: ["submetric_id"])
  metric: SingleMetric @belongsTo(fields: ["metric_id"])
}

type Grades @model @auth(rules: [{allow: public, operations: [create, read, update, delete]}]) {
  id: ID!
  studentID: ID! @index(name: "byStudent")
  evaluationID: ID! @index(name: "byEvaluation")
  date: AWSDate
  prof_id: String
  tenant_id: ID
  grades: AWSJSON
  types: AWSJSON
  examTree: AWSJSON
  totals: AWSJSON

  student: Student @belongsTo(fields: ["studentID"])
  evaluation: Evaluations @belongsTo(fields: ["evaluationID"])
}

type Debt @model @auth(rules: [{allow: public, operations: [create, read, update, delete]}]) {
  id: ID!
  studentID: ID! @index(name: "debtByStudent")
  tenant_id: ID
  price: Float
  
  student: Student @belongsTo(fields: ["studentID"])
}
